-- | TypeScript Definition Generator
--
-- This module generates TypeScript `.d.ts` files from Unison type information,
-- providing compile-time type safety for JavaScript/TypeScript consumers of
-- Unison WASM modules.
--
-- Example output:
-- @
-- // Generated by unison-wasm
-- export interface Closure<Args extends any[], Return> {
--   readonly __closure: unique symbol;
-- }
--
-- export function factorial(n: bigint): bigint;
-- export function makeButton(label: string): Widget;
--
-- export function apply<R>(closure: Closure<[], R>): R;
-- export function apply<A, R>(closure: Closure<[A], R>, arg: A): R;
-- @
module Unison.Wasm.TypeScript
  ( -- * Generation
    generateDts,
    generateDtsFromExports,
    generateModuleAugmentation,

    -- * Types
    TsType (..),
    TsExport (..),
    TsModule (..),

    -- * Type Mapping
    unisonTypeToTs,
  )
where

import Data.List (intercalate)
import Data.Text (Text)
import Data.Text qualified as Text

-- | TypeScript type representation
data TsType
  = -- | Primitive types
    TsNumber      -- ^ number (for Float, small Int)
  | TsBigInt      -- ^ bigint (for Nat, Int)
  | TsString      -- ^ string (for Text)
  | TsBoolean     -- ^ boolean
  | TsVoid        -- ^ void (for Unit)
  | TsNull        -- ^ null
  | TsUndefined   -- ^ undefined
  | TsAny         -- ^ any (fallback)
  | -- | Compound types
    TsArray TsType                    -- ^ Array<T>
  | TsOptional TsType                 -- ^ T | null
  | TsRecord [(String, TsType)]       -- ^ { field: Type, ... }
  | TsTuple [TsType]                  -- ^ [T1, T2, ...]
  | TsUnion [TsType]                  -- ^ T1 | T2 | ...
  | -- | Function/closure types
    TsClosure [TsType] TsType         -- ^ Closure<[Args], Return>
  | TsFunction [TsType] TsType        -- ^ (args) => Return
  | -- | Named types
    TsNamed String                    -- ^ Custom type name
  | TsGeneric String                  -- ^ Generic type parameter
  deriving (Eq, Show)

-- | An exported function or value
data TsExport
  = TsExportFunc
      { exportName :: String,
        exportParams :: [(String, TsType)],
        exportReturn :: TsType
      }
  | TsExportConst
      { exportName :: String,
        exportType :: TsType
      }
  deriving (Eq, Show)

-- | A complete TypeScript module definition
data TsModule = TsModule
  { -- | Module name (for documentation)
    tsModuleName :: String,
    -- | Custom type definitions (interfaces, type aliases)
    tsTypeDefs :: [String],
    -- | Exported functions and values
    tsExports :: [TsExport],
    -- | Maximum arity for apply() overloads
    tsMaxApplyArity :: Int
  }
  deriving (Eq, Show)

-- | Emit a TsType to TypeScript syntax
emitType :: TsType -> String
emitType TsNumber = "number"
emitType TsBigInt = "bigint"
emitType TsString = "string"
emitType TsBoolean = "boolean"
emitType TsVoid = "void"
emitType TsNull = "null"
emitType TsUndefined = "undefined"
emitType TsAny = "any"
emitType (TsArray t) = "Array<" ++ emitType t ++ ">"
emitType (TsOptional t) = emitType t ++ " | null"
emitType (TsRecord fields) =
  "{ " ++ intercalate ", " (map emitField fields) ++ " }"
  where
    emitField (name, t) = name ++ ": " ++ emitType t
emitType (TsTuple ts) =
  "[" ++ intercalate ", " (map emitType ts) ++ "]"
emitType (TsUnion ts) =
  intercalate " | " (map emitType ts)
emitType (TsClosure args ret) =
  "Closure<[" ++ intercalate ", " (map emitType args) ++ "], " ++ emitType ret ++ ">"
emitType (TsFunction args ret) =
  "(" ++ intercalate ", " (zipWith emitArg [0..] args) ++ ") => " ++ emitType ret
  where
    emitArg :: Int -> TsType -> String
    emitArg i t = "arg" ++ show i ++ ": " ++ emitType t
emitType (TsNamed name) = name
emitType (TsGeneric name) = name

-- | Emit an export declaration
emitExport :: TsExport -> String
emitExport (TsExportFunc name params ret) =
  "export function " ++ name ++ "(" ++ emitParams params ++ "): " ++ emitType ret ++ ";"
  where
    emitParams = intercalate ", " . map (\(n, t) -> n ++ ": " ++ emitType t)
emitExport (TsExportConst name t) =
  "export const " ++ name ++ ": " ++ emitType t ++ ";"

-- | Generate apply() overloads for closures up to maxArity
generateApplyOverloads :: Int -> [String]
generateApplyOverloads maxArity = map genOverload [0..maxArity]
  where
    genOverload :: Int -> String
    genOverload 0 =
      "export function apply<R>(closure: Closure<[], R>): R;"
    genOverload n =
      let typeParams = map (\i -> "A" ++ show i) [1..n]
          allParams = typeParams ++ ["R"]
          argList = intercalate ", " (map (\i -> "A" ++ show i) [1..n])
          funcParams = intercalate ", " $
            ("closure: Closure<[" ++ argList ++ "], R>") :
            [("arg" ++ show i ++ ": A" ++ show i) | i <- [1..n]]
      in "export function apply<" ++ intercalate ", " allParams ++ ">(" ++ funcParams ++ "): R;"

-- | The standard Closure interface definition
closureInterfaceDef :: String
closureInterfaceDef = unlines
  [ "/**"
  , " * Represents a Unison closure (partial application)."
  , " * Use apply() to invoke closures from JavaScript."
  , " */"
  , "export interface Closure<Args extends any[], Return> {"
  , "  readonly __closure: unique symbol;"
  , "  readonly __args: Args;"
  , "  readonly __return: Return;"
  , "}"
  ]

-- | The standard runtime types
runtimeTypesDef :: String
runtimeTypesDef = unlines
  [ "/** Pointer to a heap object (opaque) */"
  , "export type Ptr = number;"
  , ""
  , "/** A Unison Nat (unsigned 64-bit integer) */"
  , "export type Nat = bigint;"
  , ""
  , "/** A Unison Int (signed 64-bit integer) */"
  , "export type Int = bigint;"
  , ""
  , "/** A Unison Float (64-bit floating point) */"
  , "export type Float = number;"
  ]

-- | Generate a complete .d.ts file (legacy format)
generateDts :: TsModule -> String
generateDts m = unlines $
  [ "// Generated by unison-wasm"
  , "// Module: " ++ tsModuleName m
  , ""
  , runtimeTypesDef
  , closureInterfaceDef
  ]
  ++ tsTypeDefs m
  ++ [""]
  ++ map emitExport (tsExports m)
  ++ [""]
  ++ ["// apply() overloads for invoking closures"]
  ++ generateApplyOverloads (tsMaxApplyArity m)

-- | Generate .d.ts from a list of export names and their types (legacy)
generateDtsFromExports :: String -> [(String, [TsType], TsType)] -> String
generateDtsFromExports moduleName exports =
  generateDts TsModule
    { tsModuleName = moduleName,
      tsTypeDefs = [],
      tsExports = map toExport exports,
      tsMaxApplyArity = 3  -- Default max arity for apply()
    }
  where
    toExport (name, argTypes, retType) =
      TsExportFunc
        { exportName = name,
          exportParams = zipWith (\i t -> ("arg" ++ show i, t)) [0::Int ..] argTypes,
          exportReturn = retType
        }

-- | Generate a module augmentation .d.ts file for typed runtime.run()
--
-- This generates code that extends the FunctionSignatures interface
-- from @unison/wasm-runtime, enabling type-safe function calls.
--
-- Example output:
-- @
-- // Generated by unison-wasm
-- import '@unison/wasm-runtime';
--
-- declare module '@unison/wasm-runtime' {
--   interface FunctionSignatures {
--     'calculatePrice': (delay: bigint, qty: bigint) => [bigint, bigint, bigint];
--   }
-- }
-- @
generateModuleAugmentation :: [(String, [TsType], TsType)] -> String
generateModuleAugmentation exports = unlines $
  [ "// Generated by unison-wasm"
  , "// This file extends FunctionSignatures for type-safe runtime.run() calls"
  , ""
  , "import '@unison/wasm-runtime';"
  , ""
  , "declare module '@unison/wasm-runtime' {"
  , "  interface FunctionSignatures {"
  ]
  ++ map (("    " ++) . emitSignature) exports
  ++
  [ "  }"
  , "}"
  ]
  where
    emitSignature (name, argTypes, retType) =
      "'" ++ name ++ "': (" ++ emitParams argTypes ++ ") => " ++ emitType retType ++ ";"

    emitParams types = intercalate ", " (zipWith emitParam [0::Int ..] types)
    emitParam i t = "arg" ++ show i ++ ": " ++ emitType t

-- | Map common Unison type names to TypeScript types
unisonTypeToTs :: Text -> TsType
unisonTypeToTs typeName = case Text.unpack typeName of
  "Nat" -> TsBigInt
  "Int" -> TsBigInt
  "Float" -> TsNumber
  "Text" -> TsString
  "Boolean" -> TsBoolean
  "Unit" -> TsVoid
  "Char" -> TsString  -- Single character as string
  -- For unknown types, use the name directly
  name -> TsNamed name

