-- | Tests for TypeScript definition generation.
module Unison.Test.Wasm.TypeScript where

import Data.List (isInfixOf)
import EasyTest
import Unison.Wasm.TypeScript

test :: Test ()
test =
  scope "typescript" . tests $
    [ testEmitType,
      testEmitExport,
      testGenerateDts,
      testUnisonTypeMapping
    ]

testEmitType :: Test ()
testEmitType =
  scope "emitType" . tests $
    [ scope "primitives" . tests $
        [ scope "number" $ expectEqual (emitType TsNumber) "number",
          scope "bigint" $ expectEqual (emitType TsBigInt) "bigint",
          scope "string" $ expectEqual (emitType TsString) "string",
          scope "boolean" $ expectEqual (emitType TsBoolean) "boolean",
          scope "void" $ expectEqual (emitType TsVoid) "void"
        ],
      scope "array" $ do
        let t = TsArray TsNumber
        expectEqual (emitType t) "Array<number>",
      scope "optional" $ do
        let t = TsOptional TsString
        expectEqual (emitType t) "string | null",
      scope "closure" $ do
        let t = TsClosure [TsString] TsBigInt
        expectEqual (emitType t) "Closure<[string], bigint>",
      scope "closure_multi_arg" $ do
        let t = TsClosure [TsString, TsBigInt] TsBoolean
        expectEqual (emitType t) "Closure<[string, bigint], boolean>",
      scope "closure_no_args" $ do
        let t = TsClosure [] TsVoid
        expectEqual (emitType t) "Closure<[], void>",
      scope "named" $ do
        let t = TsNamed "Widget"
        expectEqual (emitType t) "Widget",
      scope "record" $ do
        let t = TsRecord [("name", TsString), ("age", TsBigInt)]
        expectEqual (emitType t) "{ name: string, age: bigint }",
      scope "tuple" $ do
        let t = TsTuple [TsString, TsBigInt]
        expectEqual (emitType t) "[string, bigint]",
      scope "union" $ do
        let t = TsUnion [TsString, TsBigInt]
        expectEqual (emitType t) "string | bigint"
    ]

-- Helper to emit a type to string
emitType :: TsType -> String
emitType TsNumber = "number"
emitType TsBigInt = "bigint"
emitType TsString = "string"
emitType TsBoolean = "boolean"
emitType TsVoid = "void"
emitType TsNull = "null"
emitType TsUndefined = "undefined"
emitType TsAny = "any"
emitType (TsArray t) = "Array<" ++ emitType t ++ ">"
emitType (TsOptional t) = emitType t ++ " | null"
emitType (TsRecord fields) =
  "{ " ++ unwords (zipWith emitField [0..] fields) ++ " }"
  where
    emitField :: Int -> (String, TsType) -> String
    emitField i (name, t) = 
      name ++ ": " ++ emitType t ++ if i < length fields - 1 then "," else ""
emitType (TsTuple ts) =
  "[" ++ intercalateWith ", " emitType ts ++ "]"
emitType (TsUnion ts) =
  intercalateWith " | " emitType ts
emitType (TsClosure args ret) =
  "Closure<[" ++ intercalateWith ", " emitType args ++ "], " ++ emitType ret ++ ">"
emitType (TsFunction args ret) =
  "(" ++ intercalateWith ", " emitType args ++ ") => " ++ emitType ret
emitType (TsNamed name) = name
emitType (TsGeneric name) = name

intercalateWith :: String -> (a -> String) -> [a] -> String
intercalateWith sep f xs = go xs
  where
    go [] = ""
    go [x] = f x
    go (x:rest) = f x ++ sep ++ go rest

testEmitExport :: Test ()
testEmitExport =
  scope "emitExport" . tests $
    [ scope "function_no_args" $ do
        let exp = TsExportFunc "getTime" [] TsBigInt
        let result = emitExportStr exp
        expect ("export function getTime(): bigint;" `isInfixOf` result),
      scope "function_with_args" $ do
        let exp = TsExportFunc "add" [("a", TsBigInt), ("b", TsBigInt)] TsBigInt
        let result = emitExportStr exp
        expect ("export function add(a: bigint, b: bigint): bigint;" `isInfixOf` result),
      scope "function_returns_closure" $ do
        let exp = TsExportFunc "makeAdder" [("n", TsBigInt)] (TsClosure [TsBigInt] TsBigInt)
        let result = emitExportStr exp
        expect ("Closure<[bigint], bigint>" `isInfixOf` result)
    ]

emitExportStr :: TsExport -> String
emitExportStr (TsExportFunc name params ret) =
  "export function " ++ name ++ "(" ++ emitParams params ++ "): " ++ emitType ret ++ ";"
  where
    emitParams = intercalateWith ", " (\(n, t) -> n ++ ": " ++ emitType t)
emitExportStr (TsExportConst name t) =
  "export const " ++ name ++ ": " ++ emitType t ++ ";"

testGenerateDts :: Test ()
testGenerateDts =
  scope "generateDts" . tests $
    [ scope "simple_module" $ do
        let dts = generateDtsFromExports "mylib" 
              [ ("factorial", [TsBigInt], TsBigInt)
              , ("greet", [TsString], TsString)
              ]
        -- Check module header
        expect ("// Generated by unison-wasm" `isInfixOf` dts)
        expect ("Module: mylib" `isInfixOf` dts)
        -- Check Closure interface
        expect ("interface Closure<Args extends any[], Return>" `isInfixOf` dts)
        -- Check exports
        expect ("export function factorial" `isInfixOf` dts)
        expect ("export function greet" `isInfixOf` dts)
        -- Check apply overloads
        expect ("export function apply<R>(closure: Closure<[], R>): R;" `isInfixOf` dts),
      scope "includes_runtime_types" $ do
        let dts = generateDtsFromExports "test" []
        expect ("export type Nat = bigint;" `isInfixOf` dts)
        expect ("export type Int = bigint;" `isInfixOf` dts)
        expect ("export type Float = number;" `isInfixOf` dts)
    ]

testUnisonTypeMapping :: Test ()
testUnisonTypeMapping =
  scope "unisonTypeToTs" . tests $
    [ scope "Nat" $ expectEqual (unisonTypeToTs "Nat") TsBigInt,
      scope "Int" $ expectEqual (unisonTypeToTs "Int") TsBigInt,
      scope "Float" $ expectEqual (unisonTypeToTs "Float") TsNumber,
      scope "Text" $ expectEqual (unisonTypeToTs "Text") TsString,
      scope "Boolean" $ expectEqual (unisonTypeToTs "Boolean") TsBoolean,
      scope "Unit" $ expectEqual (unisonTypeToTs "Unit") TsVoid,
      scope "custom" $ expectEqual (unisonTypeToTs "Widget") (TsNamed "Widget")
    ]

