
// Generated by unison-wasm
// Module: mathlib

/** Pointer to a heap object (opaque) */
export type Ptr = number;

/** A Unison Nat (unsigned 64-bit integer) */
export type Nat = bigint;

/** A Unison Int (signed 64-bit integer) */
export type Int = bigint;

/** A Unison Float (64-bit floating point) */
export type Float = number;

/**
 * Represents a Unison closure (partial application).
 * Use apply() to invoke closures from JavaScript.
 */
export interface Closure<Args extends any[], Return> {
  readonly __closure: unique symbol;
  readonly __args: Args;
  readonly __return: Return;
}

// Exported functions
export function factorial(n: Nat): Nat;
export function greet(name: string): string;
export function add(a: Nat, b: Nat): Nat;
export function makeAdder(n: Nat): Closure<[Nat], Nat>;

// apply() overloads for invoking closures
export function apply<R>(closure: Closure<[], R>): R;
export function apply<A1, R>(closure: Closure<[A1], R>, arg1: A1): R;
export function apply<A1, A2, R>(closure: Closure<[A1, A2], R>, arg1: A1, arg2: A2): R;
