/**
 * TypeScript Compile-Time Type Safety Tests
 * 
 * This file verifies that TypeScript catches type mismatches at compile time
 * when using generated .d.ts definitions from Unison WASM modules.
 * 
 * The tests work by:
 * 1. Creating sample .d.ts content (simulating what Unison.Wasm.TypeScript generates)
 * 2. Writing TypeScript code that uses these types
 * 3. Running tsc on both correct and incorrect code
 * 4. Verifying correct code compiles and incorrect code fails
 */

import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { join } from 'node:path';

const TEST_DIR = join(import.meta.dirname, '..', '..', '.type-safety-test');

// Sample .d.ts content (what generateDts produces)
const SAMPLE_DTS = `
// Generated by unison-wasm
// Module: mathlib

/** Pointer to a heap object (opaque) */
export type Ptr = number;

/** A Unison Nat (unsigned 64-bit integer) */
export type Nat = bigint;

/** A Unison Int (signed 64-bit integer) */
export type Int = bigint;

/** A Unison Float (64-bit floating point) */
export type Float = number;

/**
 * Represents a Unison closure (partial application).
 * Use apply() to invoke closures from JavaScript.
 */
export interface Closure<Args extends any[], Return> {
  readonly __closure: unique symbol;
  readonly __args: Args;
  readonly __return: Return;
}

// Exported functions
export function factorial(n: Nat): Nat;
export function greet(name: string): string;
export function add(a: Nat, b: Nat): Nat;
export function makeAdder(n: Nat): Closure<[Nat], Nat>;

// apply() overloads for invoking closures
export function apply<R>(closure: Closure<[], R>): R;
export function apply<A1, R>(closure: Closure<[A1], R>, arg1: A1): R;
export function apply<A1, A2, R>(closure: Closure<[A1, A2], R>, arg1: A1, arg2: A2): R;
`;

// TypeScript code that should compile successfully
const CORRECT_CODE = `
import { factorial, greet, add, makeAdder, apply, Nat, Closure } from './mathlib.js';

// Correct: Nat argument
const result1: bigint = factorial(5n);

// Correct: string argument
const greeting: string = greet("world");

// Correct: two Nat arguments
const sum: bigint = add(10n, 20n);

// Correct: get a closure
const adder: Closure<[Nat], Nat> = makeAdder(10n);

// Correct: apply closure with correct type
const applied: bigint = apply(adder, 5n);

console.log(result1, greeting, sum, applied);
`;

// TypeScript code with type errors (should NOT compile)
const INCORRECT_CODE_1 = `
import { factorial } from './mathlib.js';

// ERROR: factorial expects Nat (bigint), not number
const result = factorial(5);  // Should error: number is not bigint
`;

const INCORRECT_CODE_2 = `
import { greet } from './mathlib.js';

// ERROR: greet expects string, not number
const greeting = greet(42);  // Should error: number is not string
`;

const INCORRECT_CODE_3 = `
import { add } from './mathlib.js';

// ERROR: add expects two Nat arguments
const sum = add("hello", "world");  // Should error: string is not bigint
`;

const INCORRECT_CODE_4 = `
import { makeAdder, apply } from './mathlib.js';

const adder = makeAdder(10n);

// ERROR: apply with wrong argument type
const result = apply(adder, "wrong");  // Should error: string is not bigint
`;

const INCORRECT_CODE_5 = `
import { factorial } from './mathlib.js';

// ERROR: assigning Nat result to string
const result: string = factorial(5n);  // Should error: bigint not assignable to string
`;

// Minimal tsconfig for testing
const TSCONFIG = `{
  "compilerOptions": {
    "strict": true,
    "noEmit": true,
    "moduleResolution": "node",
    "module": "ESNext",
    "target": "ESNext",
    "lib": ["ESNext"]
  },
  "include": ["*.ts"]
}`;

// Helper to run tsc with consistent options
function runTsc(filename: string): { success: boolean; output: string } {
  try {
    const result = execSync(
      `npx tsc --noEmit --target ESNext --moduleResolution node --strict ${filename}`,
      {
        cwd: TEST_DIR,
        encoding: 'utf-8',
        stdio: 'pipe'
      }
    );
    return { success: true, output: result };
  } catch (error: any) {
    return { success: false, output: error.stdout || error.stderr || '' };
  }
}

describe('TypeScript Compile-Time Type Safety', () => {
  before(() => {
    // Create test directory
    if (existsSync(TEST_DIR)) {
      rmSync(TEST_DIR, { recursive: true });
    }
    mkdirSync(TEST_DIR, { recursive: true });
    
    // Write the .d.ts file
    writeFileSync(join(TEST_DIR, 'mathlib.d.ts'), SAMPLE_DTS);
    
    // Write tsconfig
    writeFileSync(join(TEST_DIR, 'tsconfig.json'), TSCONFIG);
  });

  after(() => {
    // Cleanup
    if (existsSync(TEST_DIR)) {
      rmSync(TEST_DIR, { recursive: true });
    }
  });

  it('correct code compiles without errors', () => {
    writeFileSync(join(TEST_DIR, 'correct.ts'), CORRECT_CODE);
    const { success, output } = runTsc('correct.ts');
    assert.ok(success, `Correct code should compile but got error: ${output}`);
  });

  it('catches wrong argument type (number instead of bigint)', () => {
    writeFileSync(join(TEST_DIR, 'wrong1.ts'), INCORRECT_CODE_1);
    const { success, output } = runTsc('wrong1.ts');
    assert.ok(!success, 'Should have failed to compile');
    assert.ok(output.includes('error TS'), 'TypeScript should report an error');
  });

  it('catches wrong argument type (number instead of string)', () => {
    writeFileSync(join(TEST_DIR, 'wrong2.ts'), INCORRECT_CODE_2);
    const { success, output } = runTsc('wrong2.ts');
    assert.ok(!success, 'Should have failed to compile');
    assert.ok(output.includes('error TS'), 'TypeScript should report an error');
  });

  it('catches wrong argument type (string instead of bigint)', () => {
    writeFileSync(join(TEST_DIR, 'wrong3.ts'), INCORRECT_CODE_3);
    const { success, output } = runTsc('wrong3.ts');
    assert.ok(!success, 'Should have failed to compile');
    assert.ok(output.includes('error TS'), 'TypeScript should report an error');
  });

  it('catches wrong closure argument type', () => {
    writeFileSync(join(TEST_DIR, 'wrong4.ts'), INCORRECT_CODE_4);
    const { success, output } = runTsc('wrong4.ts');
    assert.ok(!success, 'Should have failed to compile');
    assert.ok(output.includes('error TS'), 'TypeScript should report an error');
  });

  it('catches wrong return type assignment', () => {
    writeFileSync(join(TEST_DIR, 'wrong5.ts'), INCORRECT_CODE_5);
    const { success, output } = runTsc('wrong5.ts');
    assert.ok(!success, 'Should have failed to compile');
    assert.ok(output.includes('error TS'), 'TypeScript should report an error');
  });
});

describe('Closure Type Safety', () => {
  before(() => {
    // Ensure test directory exists
    if (!existsSync(TEST_DIR)) {
      mkdirSync(TEST_DIR, { recursive: true });
      writeFileSync(join(TEST_DIR, 'mathlib.d.ts'), SAMPLE_DTS);
      writeFileSync(join(TEST_DIR, 'tsconfig.json'), TSCONFIG);
    }
  });

  it('closure types preserve argument and return types', () => {
    const code = `
import { makeAdder, apply, Closure, Nat } from './mathlib.js';

const adder: Closure<[Nat], Nat> = makeAdder(10n);

// This should compile: correct types
const result: bigint = apply(adder, 5n);

// Type inference should work
const inferred = apply(adder, 15n);
const check: bigint = inferred;  // Should be bigint
`;
    writeFileSync(join(TEST_DIR, 'closure_correct.ts'), code);
    const { success, output } = runTsc('closure_correct.ts');
    assert.ok(success, `Closure types should work: ${output}`);
  });

  it('prevents passing closure where function expected', () => {
    const code = `
import { makeAdder, factorial, Closure, Nat } from './mathlib.js';

const adder: Closure<[Nat], Nat> = makeAdder(10n);

// ERROR: Cannot use closure directly as a function
const result = adder(5n);  // Should error: Closure is not callable
`;
    writeFileSync(join(TEST_DIR, 'closure_not_callable.ts'), code);
    const { success, output } = runTsc('closure_not_callable.ts');
    assert.ok(!success, 'Should have failed - closures should not be directly callable');
    assert.ok(output.includes('error TS'), 'TypeScript should report an error');
  });

  it('prevents wrong arity in apply', () => {
    const code = `
import { makeAdder, apply } from './mathlib.js';

const adder = makeAdder(10n);

// ERROR: Too many arguments
const result = apply(adder, 5n, 10n);  // Should error: expects 1 arg, got 2
`;
    writeFileSync(join(TEST_DIR, 'closure_wrong_arity.ts'), code);
    const { success, output } = runTsc('closure_wrong_arity.ts');
    assert.ok(!success, 'Should have failed - wrong arity');
    assert.ok(output.includes('error TS'), 'TypeScript should report an error');
  });
});

