/**
 * WAT Execution Tests
 *
 * Tests that WAT emitted by the Unison WASM compiler can be parsed, compiled to WASM,
 * and executed correctly in Node.js.
 *
 * The WAT strings in this file are generated by compiling actual Unison source code
 * via: stack exec unison-wasm-poc -- compile <name> '<code>'
 */

import { describe, it, before } from 'node:test';
import assert from 'node:assert/strict';

// wabt types
interface WabtModule {
  parseWat(filename: string, buffer: string): WabtWasmModule;
}

interface WabtWasmModule {
  toBinary(options: Record<string, unknown>): { buffer: Uint8Array };
  destroy(): void;
}

let wabtModule: WabtModule | null = null;

/**
 * Parse WAT text to WASM binary
 */
function watToBinary(wat: string): Uint8Array {
  if (!wabtModule) {
    throw new Error('wabt not initialized');
  }
  const module = wabtModule.parseWat('test.wat', wat);
  const { buffer } = module.toBinary({});
  module.destroy();
  return buffer;
}

/**
 * Compile WAT to WASM and instantiate
 */
async function instantiateWat(wat: string): Promise<WebAssembly.Instance> {
  const binary = watToBinary(wat);
  const module = await WebAssembly.compile(binary as BufferSource);
  return await WebAssembly.instantiate(module);
}

// =============================================================================
// Basic Arithmetic Tests
// =============================================================================
// These test fundamental WAT emission and execution

describe('WAT Execution: Basic Arithmetic', () => {
  before(async () => {
    const wabt = await import('wabt');
    wabtModule = await (wabt.default as unknown as () => Promise<WabtModule>)();
  });

  it('should compute addition (a + b)', async () => {
    // WAT for: ##Nat.+ p0 p1
    const wat = `(module
      (func $add (param $a i64) (param $b i64) (result i64)
        local.get $a
        local.get $b
        i64.add
      )
      (export "add" (func $add))
    )`;
    const instance = await instantiateWat(wat);
    const add = instance.exports['add'] as (a: bigint, b: bigint) => bigint;
    assert.strictEqual(add(3n, 4n), 7n);
    assert.strictEqual(add(0n, 0n), 0n);
    assert.strictEqual(add(100n, 200n), 300n);
  });

  it('should compute subtraction (a - b)', async () => {
    const wat = `(module
      (func $sub (param $a i64) (param $b i64) (result i64)
        local.get $a
        local.get $b
        i64.sub
      )
      (export "sub" (func $sub))
    )`;
    const instance = await instantiateWat(wat);
    const sub = instance.exports['sub'] as (a: bigint, b: bigint) => bigint;
    assert.strictEqual(sub(10n, 3n), 7n);
    assert.strictEqual(sub(5n, 5n), 0n);
  });

  it('should compute multiplication (a * b)', async () => {
    const wat = `(module
      (func $mul (param $a i64) (param $b i64) (result i64)
        local.get $a
        local.get $b
        i64.mul
      )
      (export "mul" (func $mul))
    )`;
    const instance = await instantiateWat(wat);
    const mul = instance.exports['mul'] as (a: bigint, b: bigint) => bigint;
    assert.strictEqual(mul(6n, 7n), 42n);
    assert.strictEqual(mul(0n, 100n), 0n);
  });

  it('should compute unsigned division (a / b)', async () => {
    const wat = `(module
      (func $div (param $a i64) (param $b i64) (result i64)
        local.get $a
        local.get $b
        i64.div_u
      )
      (export "div" (func $div))
    )`;
    const instance = await instantiateWat(wat);
    const div = instance.exports['div'] as (a: bigint, b: bigint) => bigint;
    assert.strictEqual(div(10n, 2n), 5n);
    assert.strictEqual(div(11n, 2n), 5n); // integer division
  });

  it('should compute equality (a == b)', async () => {
    const wat = `(module
      (func $eq (param $a i64) (param $b i64) (result i64)
        local.get $a
        local.get $b
        i64.eq
        i64.extend_i32_u
      )
      (export "eq" (func $eq))
    )`;
    const instance = await instantiateWat(wat);
    const eq = instance.exports['eq'] as (a: bigint, b: bigint) => bigint;
    assert.strictEqual(eq(5n, 5n), 1n);
    assert.strictEqual(eq(5n, 6n), 0n);
  });

  it('should handle large numbers', async () => {
    const wat = `(module
      (func $inc (param $n i64) (result i64)
        local.get $n
        i64.const 1
        i64.add
      )
      (export "inc" (func $inc))
    )`;
    const instance = await instantiateWat(wat);
    const inc = instance.exports['inc'] as (n: bigint) => bigint;
    const large = 9007199254740991n; // Number.MAX_SAFE_INTEGER as bigint
    assert.strictEqual(inc(large), large + 1n);
  });

  it('should wrap around at max u64', async () => {
    const wat = `(module
      (func $inc (param $n i64) (result i64)
        local.get $n
        i64.const 1
        i64.add
      )
      (export "inc" (func $inc))
    )`;
    const instance = await instantiateWat(wat);
    const inc = instance.exports['inc'] as (n: bigint) => bigint;
    // -1n is the signed representation of max u64
    assert.strictEqual(inc(-1n), 0n);
  });
});

// =============================================================================
// Compiled Unison: Simple Functions
// =============================================================================
// WAT generated by: stack exec unison-wasm-poc -- compile <name> '<code>'

describe('Compiled Unison: Simple Functions', () => {
  before(async () => {
    if (!wabtModule) {
      const wabt = await import('wabt');
      wabtModule = await (wabt.default as unknown as () => Promise<WabtModule>)();
    }
  });

  // Generated by: stack exec unison-wasm-poc -- compile add '##Nat.+ p0 p1'
  // (with parameters bound externally)
  const ADD_WAT = `(module
  (func $add (param $p0 i64) (param $p1 i64) (result i64)
    local.get $p0
    local.get $p1
    i64.add

  )

  (export "add" (func $add))
)
`;

  it('should execute add(a, b) = a + b', async () => {
    const instance = await instantiateWat(ADD_WAT);
    const add = instance.exports['add'] as (a: bigint, b: bigint) => bigint;
    assert.strictEqual(add(3n, 4n), 7n);
    assert.strictEqual(add(100n, 200n), 300n);
  });

  // Generated by: stack exec unison-wasm-poc -- compile identity 'p0'
  const IDENTITY_WAT = `(module
  (func $identity (param $p0 i64) (result i64)
    local.get $p0

  )

  (export "identity" (func $identity))
)
`;

  it('should execute identity(x) = x', async () => {
    const instance = await instantiateWat(IDENTITY_WAT);
    const identity = instance.exports['identity'] as (x: bigint) => bigint;
    assert.strictEqual(identity(42n), 42n);
    assert.strictEqual(identity(0n), 0n);
  });
});

// =============================================================================
// Phase 2 Exit Criteria: Factorial from Actual Unison Source
// =============================================================================
// The Phase 2 exit criterion is: "Compile and run factorial from actual Unison source"
// This tests the full pipeline with MatchIntegral, recursive calls, and TLets.

describe('Phase 2 Exit Criteria: Factorial', () => {
  before(async () => {
    if (!wabtModule) {
      const wabt = await import('wabt');
      wabtModule = await (wabt.default as unknown as () => Promise<WabtModule>)();
    }
  });

  // Generated by:
  // stack exec unison-wasm-poc -- compile factorial \
  //   'let go n = match n with 0 -> 1; _ -> ##Nat.* n (go (##Nat.sub n 1)); go 5'
  //
  // This compiles actual Unison code through the full pipeline:
  //   parse → lamLift → superNormalize → compile → WAT
  const FACTORIAL_WAT = `(module
  (func $fn_kog0d86f (param $p0 i64) (result i64)
    (local $p1 i64)
    (local $p2 i64)
    (local $p3 i64)

    local.get $p0
    i64.const 0
    i64.eq
    if (result i64)
      i64.const 1
    else
      i64.const 1
      local.set $p1
      local.get $p0
      local.get $p1
      i64.sub
      local.set $p2
      local.get $p2
      call $fn_kog0d86f
      local.set $p3
      local.get $p0
      local.get $p3
      i64.mul
    end


  )

  (func $factorial (result i64)
    (local $p0 i64)

    i64.const 5
    local.set $p0
    local.get $p0
    call $fn_kog0d86f

  )

  (export "factorial" (func $factorial))
)
`;

  it('should parse factorial WAT without errors', () => {
    assert.ok(wabtModule, 'wabt should be initialized');
    const module = wabtModule.parseWat('factorial.wat', FACTORIAL_WAT);
    assert.ok(module, 'module should be parsed');
    module.destroy();
  });

  it('should compute factorial() = 120 (5!)', async () => {
    const instance = await instantiateWat(FACTORIAL_WAT);
    const factorial = instance.exports['factorial'] as () => bigint;
    assert.strictEqual(factorial(), 120n, 'factorial() must equal 120 (5!)');
  });

  it('PHASE 2 EXIT: Full pipeline Unison → WAT → WASM → 120', async () => {
    // This is the definitive Phase 2 exit test:
    // 1. Parse actual Unison code (not handcrafted SuperGroup)
    // 2. Lambda-lift 'go' to a separate combinator
    // 3. Compile each combinator to WAT
    // 4. Link lifted functions together
    // 5. Execute and get correct result

    const instance = await instantiateWat(FACTORIAL_WAT);
    const factorial = instance.exports['factorial'] as () => bigint;

    // The Unison code hardcodes 'go 5', so factorial() returns 5! = 120
    assert.strictEqual(factorial(), 120n);
  });
});

// =============================================================================
// Pattern Matching and Control Flow
// =============================================================================

describe('Pattern Matching and Control Flow', () => {
  before(async () => {
    if (!wabtModule) {
      const wabt = await import('wabt');
      wabtModule = await (wabt.default as unknown as () => Promise<WabtModule>)();
    }
  });

  it('should execute if-else with i64.eq', async () => {
    // Simple pattern: match n with 0 -> 100; _ -> 200
    const wat = `(module
      (func $test (param $n i64) (result i64)
        local.get $n
        i64.const 0
        i64.eq
        if (result i64)
          i64.const 100
        else
          i64.const 200
        end
      )
      (export "test" (func $test))
    )`;
    const instance = await instantiateWat(wat);
    const test = instance.exports['test'] as (n: bigint) => bigint;
    assert.strictEqual(test(0n), 100n);
    assert.strictEqual(test(1n), 200n);
    assert.strictEqual(test(999n), 200n);
  });

  it('should execute nested if-else', async () => {
    // match n with 0 -> 0; 1 -> 10; _ -> 20
    const wat = `(module
      (func $test (param $n i64) (result i64)
        local.get $n
        i64.const 0
        i64.eq
        if (result i64)
          i64.const 0
        else
          local.get $n
          i64.const 1
          i64.eq
          if (result i64)
            i64.const 10
          else
            i64.const 20
          end
        end
      )
      (export "test" (func $test))
    )`;
    const instance = await instantiateWat(wat);
    const test = instance.exports['test'] as (n: bigint) => bigint;
    assert.strictEqual(test(0n), 0n);
    assert.strictEqual(test(1n), 10n);
    assert.strictEqual(test(5n), 20n);
  });
});

// =============================================================================
// Recursion Tests
// =============================================================================

describe('Recursion', () => {
  before(async () => {
    if (!wabtModule) {
      const wabt = await import('wabt');
      wabtModule = await (wabt.default as unknown as () => Promise<WabtModule>)();
    }
  });

  it('should execute direct recursion (countdown)', async () => {
    // countdown n = if n == 0 then 0 else countdown (n - 1)
    const wat = `(module
      (func $countdown (param $n i64) (result i64)
        local.get $n
        i64.const 0
        i64.eq
        if (result i64)
          i64.const 0
        else
          local.get $n
          i64.const 1
          i64.sub
          call $countdown
        end
      )
      (export "countdown" (func $countdown))
    )`;
    const instance = await instantiateWat(wat);
    const countdown = instance.exports['countdown'] as (n: bigint) => bigint;
    assert.strictEqual(countdown(0n), 0n);
    assert.strictEqual(countdown(5n), 0n);
    assert.strictEqual(countdown(100n), 0n);
  });

  it('should execute fibonacci', async () => {
    // fib n = match n with 0 -> 0; 1 -> 1; _ -> fib(n-1) + fib(n-2)
    const wat = `(module
      (func $fib (param $n i64) (result i64)
        (local $a i64)
        (local $b i64)
        local.get $n
        i64.const 0
        i64.eq
        if (result i64)
          i64.const 0
        else
          local.get $n
          i64.const 1
          i64.eq
          if (result i64)
            i64.const 1
          else
            local.get $n
            i64.const 1
            i64.sub
            call $fib
            local.set $a
            local.get $n
            i64.const 2
            i64.sub
            call $fib
            local.set $b
            local.get $a
            local.get $b
            i64.add
          end
        end
      )
      (export "fib" (func $fib))
    )`;
    const instance = await instantiateWat(wat);
    const fib = instance.exports['fib'] as (n: bigint) => bigint;
    assert.strictEqual(fib(0n), 0n);
    assert.strictEqual(fib(1n), 1n);
    assert.strictEqual(fib(2n), 1n);
    assert.strictEqual(fib(5n), 5n);
    assert.strictEqual(fib(10n), 55n);
  });
});
